"""Report generator for gap analysis results."""

import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional

import yaml

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates formatted reports from gap analysis results."""

    def __init__(self, results: Dict[str, Any]):
        """
        Initialize the report generator.

        Args:
            results: Analysis results from GapEngine.get_results()
        """
        self.results = results

    def generate_markdown(self) -> str:
        """
        Generate a comprehensive Markdown report with executive summary,
        gap matrix, priority backlog, and detection rule stubs.

        Returns:
            Markdown formatted report string
        """
        lines = []

        # Metadata header
        if '_metadata' in self.results:
            lines.append("<!-- Generated by MITRE ATT&CK Coverage Gap Analyzer -->")
            lines.append(f"<!-- Exported: {self.results['_metadata']['exported_at']} -->")
            lines.append("")

        # Executive Summary
        lines.append("# MITRE ATT&CK Coverage Gap Analysis Report")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"**Overall Coverage:** {self.results['overall_coverage']}%")
        lines.append(f"**Total Techniques:** {self.results['total_techniques']}")
        lines.append(f"**Covered Techniques:** {self.results['covered_techniques']}")
        lines.append(f"**Uncovered Techniques:** {self.results['uncovered_techniques']}")
        lines.append("")

        # Risk Assessment
        uncovered_pct = 100 - self.results['overall_coverage']
        if uncovered_pct == 0:
            risk_level = "LOW"
            risk_color = "green"
        elif uncovered_pct < 20:
            risk_level = "MEDIUM"
            risk_color = "orange"
        elif uncovered_pct < 50:
            risk_level = "HIGH"
            risk_color = "darkorange"
        else:
            risk_level = "CRITICAL"
            risk_color = "red"

        lines.append(f"**Risk Assessment:** :{risk_color[0]}: {risk_level}")
        lines.append("")
        lines.append("### Key Findings")
        lines.append("")
        lines.append(f"- {self.results['uncovered_techniques']} techniques require detection coverage")
        lines.append(f"- {len(self.results['tactics'])} MITRE tactics analyzed")

        # Find tactics with lowest coverage
        worst_tactic = min(self.results['tactics'], key=lambda x: x['coverage_percentage'])
        lines.append(f"- Lowest coverage tactic: **{worst_tactic['tactic_name']}** ({worst_tactic['coverage_percentage']}%)")
        lines.append("")

        # Gap Matrix
        lines.append("## Gap Matrix by Tactic")
        lines.append("")
        lines.append("| Tactic | Total | Covered | Uncovered | Coverage % | Status |")
        lines.append("|--------|-------|---------|-----------|------------|--------|")

        for tactic in self.results["tactics"]:
            status = "✅" if tactic["coverage_percentage"] >= 80 else "⚠️" if tactic["coverage_percentage"] >= 50 else "🔴"
            lines.append(
                f"| {tactic['tactic_name']} | {tactic['total_techniques']} | "
                f"{tactic['covered_techniques']} | {tactic['uncovered_techniques']} | "
                f"{tactic['coverage_percentage']}% | {status} |"
            )

        lines.append("")

        # Priority Backlog
        lines.append("## Priority Backlog")
        lines.append("")
        lines.append("Top uncovered techniques prioritized by risk score:")
        lines.append("")
        lines.append("| Priority | Technique ID | Name | Score | Tactic |")
        lines.append("|----------|--------------|------|-------|--------|")

        scored = self.results.get('scored_techniques', [])
        for tech in scored[:15]:  # Top 15
            priority = tech.get('priority', 'UNKNOWN')
            lines.append(
                f"| {priority} | {tech['technique_id']} | {tech['technique_name']} | "
                f"{tech.get('score', 'N/A')} | {tech.get('tactic_name', 'N/A')} |"
            )

        if len(scored) > 15:
            lines.append(f"| ... and {len(scored) - 15} more techniques | | | | |")

        lines.append("")

        # Detection Rule Stubs
        lines.append("## Detection Rule Stubs")
        lines.append("")
        lines.append("Below are ready-to-customize detection rule templates for the highest priority uncovered techniques.")
        lines.append("")

        for tech in scored[:5]:  # Top 5 techniques
            lines.append(f"### {tech['technique_id']}: {tech['technique_name']}")
            lines.append("")
            lines.append(f"**Tactic:** {tech.get('tactic_name', 'N/A')}")
            lines.append(f"**Priority:** {tech.get('priority', 'N/A')}")
            lines.append(f"**Score:** {tech.get('score', 'N/A')}")
            lines.append("")
            lines.append("#### Sigma Rule Template")
            lines.append("```yaml")
            lines.append(f"title: Detect {tech['technique_name']} ({tech['technique_id']})")
            lines.append("id: REPLACE-WITH-UUID")
            lines.append("status: experimental")
            lines.append("description: Detects potential {tech['technique_name']} activity")
            lines.append("author: Security Team")
            lines.append("date: 2026-09-09")
            lines.append("references:")
            lines.append(f"  - https://attack.mitre.org/techniques/{tech['technique_id']}/")
            lines.append("tags:")
            lines.append("  - attack.tactic")
            lines.append(f"  - attack.{tech.get('tactic_shortname', 'unknown')}")
            lines.append("detection:")
            lines.append("  selection:")
            lines.append("    # Add your detection logic here")
            lines.append("  condition: selection")
            lines.append("falsepositives:")
            lines.append("  # List potential false positives")
            lines.append("level: medium")
            lines.append("```")
            lines.append("")

            lines.append("#### Elasticsearch Rule Template")
            lines.append("```json")
            lines.append("{")
            lines.append('  "rule_id": "REPLACE-WITH-ID",')
            lines.append(f'  "description": "Detect {tech["technique_name"]} ({tech["technique_id"]})",')
            lines.append('  "severity": "medium",')
            lines.append('  "type": "query",')
            lines.append('  "query": "ADD-YOUR-ELASTICSEARCH-QUERY-HERE"')
            lines.append("}")
            lines.append("```")
            lines.append("")

            lines.append("#### Splunk Search Template")
            lines.append("```spl")
            lines.append(f"index=main sourcetype=REPLACE | ... | search ...")
            lines.append(f"# Detect {tech['technique_name']} ({tech['technique_id']})")
            lines.append("```")
            lines.append("")
            lines.append("---")
            lines.append("")

        # Detailed Tactic Breakdown
        lines.append("## Detailed Tactic Breakdown")
        lines.append("")

        for tactic in self.results["tactics"]:
            lines.append(f"### {tactic['tactic_name']} ({tactic['tactic_shortname']})")
            lines.append("")
            lines.append(f"**Coverage:** {tactic['coverage_percentage']}%")
            lines.append(f"**Techniques:** {tactic['covered_techniques']} covered / {tactic['total_techniques']} total")
            lines.append("")

            if tactic["uncovered_technique_ids"]:
                lines.append("**Uncovered Techniques:**")
                for tech_id in tactic["uncovered_technique_ids"][:10]:
                    lines.append(f"- {tech_id}")
                if len(tactic["uncovered_technique_ids"]) > 10:
                    lines.append(f"- ... and {len(tactic['uncovered_technique_ids']) - 10} more")
            else:
                lines.append("All techniques covered! ✅")
            lines.append("")

        return "\n".join(lines)

    def generate_json(self) -> str:
        """
        Generate a JSON report.

        Returns:
            JSON formatted report string
        """
        return json.dumps(self.results, indent=2, ensure_ascii=False)

    def generate_html(self) -> str:
        """
        Generate a comprehensive HTML report with executive summary,
        gap matrix, priority backlog, and detection rule stubs.

        Returns:
            HTML formatted report string
        """
        html = []
        html.append("<!DOCTYPE html>")
        html.append("<html lang='en'>")
        html.append("<head>")
        html.append("    <meta charset='UTF-8'>")
        html.append("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
        html.append("    <title>MITRE ATT&CK Coverage Gap Analysis Report</title>")
        html.append("    <style>")
        html.append("        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }")
        html.append("        h1, h2, h3 { color: #2c3e50; }")
        html.append("        h1 { border-bottom: 2px solid #3498db; padding-bottom: 10px; }")
        html.append("        h2 { border-bottom: 1px solid #ddd; padding-bottom: 5px; }")
        html.append("        table { border-collapse: collapse; width: 100%; margin: 20px 0; }")
        html.append("        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }")
        html.append("        th { background-color: #f2f2f2; }")
        html.append("        tr:nth-child(even) { background-color: #f9f9f9; }")
        html.append("        .coverage-high { color: #27ae60; font-weight: bold; }")
        html.append("        .coverage-medium { color: #f39c12; font-weight: bold; }")
        html.append("        .coverage-low { color: #e74c3c; font-weight: bold; }")
        html.append("        .summary { background-color: #ecf0f1; padding: 20px; border-radius: 5px; margin-bottom: 20px; }")
        html.append("        .risk-critical { background-color: #ffebee; padding: 15px; border-left: 4px solid #e74c3c; margin: 15px 0; }")
        html.append("        .risk-high { background-color: #fff3e0; padding: 15px; border-left: 4px solid #f39c12; margin: 15px 0; }")
        html.append("        .risk-medium { background-color: #e8f5e9; padding: 15px; border-left: 4px solid #27ae60; margin: 15px 0; }")
        html.append("        code { background-color: #f4f4f4; padding: 2px 6px; border-radius: 3px; }")
        html.append("        pre { background-color: #2d2d2d; color: #f8f8f2; padding: 15px; border-radius: 5px; overflow-x: auto; }")
        html.append("        .technique-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 15px; }")
        html.append("        .technique-card { border: 1px solid #ddd; border-radius: 5px; padding: 15px; background-color: #fafafa; }")
        html.append("    </style>")
        html.append("</head>")
        html.append("<body>")
        html.append("    <h1>MITRE ATT&CK Coverage Gap Analysis Report</h1>")

        # Executive Summary
        html.append("    <div class='summary'>")
        html.append(f"        <h2>Executive Summary</h2>")
        html.append(f"        <p><strong>Overall Coverage:</strong> {self.results['overall_coverage']}%</p>")
        html.append(f"        <p><strong>Total Techniques:</strong> {self.results['total_techniques']}</p>")
        html.append(f"        <p><strong>Covered Techniques:</strong> {self.results['covered_techniques']}</p>")
        html.append(f"        <p><strong>Uncovered Techniques:</strong> {self.results['uncovered_techniques']}</p>")
        html.append("    </div>")

        # Risk Assessment
        uncovered_pct = 100 - self.results['overall_coverage']
        if uncovered_pct == 0:
            risk_level = "LOW"
            risk_class = "risk-medium"
        elif uncovered_pct < 20:
            risk_level = "MEDIUM"
            risk_class = "risk-medium"
        elif uncovered_pct < 50:
            risk_level = "HIGH"
            risk_class = "risk-high"
        else:
            risk_level = "CRITICAL"
            risk_class = "risk-critical"

        html.append(f"    <div class='{risk_class}'>")
        html.append(f"        <h3>Risk Assessment: {risk_level}</h3>")
        html.append(f"        <p>{self.results['uncovered_techniques']} techniques require detection coverage across {len(self.results['tactics'])} MITRE tactics.</p>")
        html.append("    </div>")

        # Gap Matrix
        html.append("    <h2>Gap Matrix by Tactic</h2>")
        html.append("    <table>")
        html.append("        <thead>")
        html.append("            <tr>")
        html.append("                <th>Tactic</th>")
        html.append("                <th>Total</th>")
        html.append("                <th>Covered</th>")
        html.append("                <th>Uncovered</th>")
        html.append("                <th>Coverage %</th>")
        html.append("                <th>Status</th>")
        html.append("            </tr>")
        html.append("        </thead>")
        html.append("        <tbody>")

        for tactic in self.results["tactics"]:
            status = "✅" if tactic["coverage_percentage"] >= 80 else "⚠️" if tactic["coverage_percentage"] >= 50 else "🔴"
            html.append("        <tr>")
            html.append(f"            <td>{tactic['tactic_name']}</td>")
            html.append(f"            <td>{tactic['total_techniques']}</td>")
            html.append(f"            <td>{tactic['covered_techniques']}</td>")
            html.append(f"            <td>{tactic['uncovered_techniques']}</td>")
            html.append(f"            <td>{tactic['coverage_percentage']}%</td>")
            html.append(f"            <td>{status}</td>")
            html.append("        </tr>")

        html.append("        </tbody>")
        html.append("    </table>")

        # Priority Backlog
        html.append("    <h2>Priority Backlog</h2>")
        html.append("    <p>Top uncovered techniques prioritized by risk score:</p>")
        html.append("    <table>")
        html.append("        <thead>")
        html.append("            <tr>")
        html.append("                <th>Priority</th>")
        html.append("                <th>Technique ID</th>")
        html.append("                <th>Name</th>")
        html.append("                <th>Score</th>")
        html.append("                <th>Tactic</th>")
        html.append("            </tr>")
        html.append("        </thead>")
        html.append("        <tbody>")

        scored = self.results.get('scored_techniques', [])
        for tech in scored[:15]:
            html.append("        <tr>")
            html.append(f"            <td>{tech.get('priority', 'UNKNOWN')}</td>")
            html.append(f"            <td>{tech['technique_id']}</td>")
            html.append(f"            <td>{tech['technique_name']}</td>")
            html.append(f"            <td>{tech.get('score', 'N/A')}</td>")
            html.append(f"            <td>{tech.get('tactic_name', 'N/A')}</td>")
            html.append("        </tr>")

        html.append("        </tbody>")
        html.append("    </table>")

        # Detection Rule Stubs
        html.append("    <h2>Detection Rule Stubs</h2>")
        html.append("    <p>Ready-to-customize detection rule templates for top priority uncovered techniques:</p>")

        for tech in scored[:5]:
            html.append(f"    <div class='technique-card'>")
            html.append(f"        <h3>{tech['technique_id']}: {tech['technique_name']}</h3>")
            html.append(f"        <p><strong>Tactic:</strong> {tech.get('tactic_name', 'N/A')}</p>")
            html.append(f"        <p><strong>Priority:</strong> {tech.get('priority', 'N/A')}</p>")
            html.append(f"        <p><strong>Score:</strong> {tech.get('score', 'N/A')}</p>")
            html.append("        <h4>Sigma Rule Template</h4>")
            html.append("        <pre>")
            html.append(f"title: Detect {tech['technique_name']} ({tech['technique_id']})")
            html.append("id: REPLACE-WITH-UUID")
            html.append("status: experimental")
            html.append(f"description: Detects potential {tech['technique_name']} activity")
            html.append("author: Security Team")
            html.append("date: 2026-09-09")
            html.append("references:")
            html.append(f"  - https://attack.mitre.org/techniques/{tech['technique_id']}/")
            html.append("tags:")
            html.append("  - attack.tactic")
            html.append(f"  - attack.{tech.get('tactic_shortname', 'unknown')}")
            html.append("detection:")
            html.append("  selection:")
            html.append("    # Add your detection logic here")
            html.append("  condition: selection")
            html.append("falsepositives:")
            html.append("  # List potential false positives")
            html.append("level: medium")
            html.append("        </pre>")
            html.append("    </div>")

        # Detailed Tactic Breakdown
        html.append("    <h2>Detailed Tactic Breakdown</h2>")

        for tactic in self.results["tactics"]:
            html.append(f"    <h3>{tactic['tactic_name']} ({tactic['tactic_shortname']})</h3>")
            html.append(f"    <p><strong>Coverage:</strong> {tactic['coverage_percentage']}%</p>")
            html.append(f"    <p><strong>Techniques:</strong> {tactic['covered_techniques']} covered / {tactic['total_techniques']} total</p>")

            if tactic["uncovered_technique_ids"]:
                html.append("        <p><strong>Uncovered Techniques:</strong></p>")
                html.append("        <ul>")
                for tech_id in tactic["uncovered_technique_ids"][:10]:
                    html.append(f"            <li>{tech_id}</li>")
                if len(tactic["uncovered_technique_ids"]) > 10:
                    html.append(f"            <li>... and {len(tactic['uncovered_technique_ids']) - 10} more</li>")
                html.append("        </ul>")
            else:
                html.append("        <p>All techniques covered! ✅</p>")

        html.append("</body>")
        html.append("</html>")

        return "\n".join(html)

    def save_report(self, content: str, output_path: Path, format_type: str) -> None:
        """
        Save report to file.

        Args:
            content: Report content string
            output_path: Path to save the report
            format_type: Format type (md, json, html)
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"Report saved to {output_path}")